-- setup_snowflake_simple.sql
-- للمشروع البسيط بتاعك

-- إنشاء قاعدة البيانات
CREATE DATABASE IF NOT EXISTS ANALYTICS_DB;

-- استخدام قاعدة البيانات
USE DATABASE ANALYTICS_DB;

-- إنشاء schemas
CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STAGING;
CREATE SCHEMA IF NOT EXISTS SILVER;
CREATE SCHEMA IF NOT EXISTS GOLD;

-- إنشاء جدول RAW
CREATE TABLE IF NOT EXISTS RAW.REAL_FLIGHTS (
    ID VARCHAR,
    ORIGIN VARCHAR(3),
    DESTINATION VARCHAR(3),
    DEPARTURE_DATE DATE,
    DEPARTURE_TIME VARCHAR,
    LOADED_AT TIMESTAMP,
    PRICE FLOAT,
    CURRENCY VARCHAR(3),
    AIRLINE VARCHAR(10),
    STOPS INTEGER,
    DATA_SOURCE VARCHAR,
    RAW_DATA VARIANT,
    BATCH_ID VARCHAR,
    SOURCE_FILE VARCHAR
);

-- منح الصلاحيات
GRANT ALL PRIVILEGES ON DATABASE ANALYTICS_DB TO ROLE SYSADMIN;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE ANALYTICS_DB TO ROLE SYSADMIN;